OPENAI_API_KEY = "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"
TEXT_VECTORSTORE_PATH = "data\deeplake_text_vectorstore"
CHARACTER_SPLITTER_CHUNK_SIZE = 75
OPENAI_EMBEDDINGS_CHUNK_SIZE = 16
TEXT_COLUMN_NAME = "TextData"